# Generated by Django 5.2.1 on 2025-05-30 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Tujuan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('priority', models.IntegerField(default=0, help_text='Semakin tinggi angka, semakin tinggi prioritas', verbose_name='Prioritas')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Target Selesai')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Sudah Selesai')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Sub-Tugas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Sub-Tugas')),
                ('priority', models.IntegerField(default=0, help_text='Prioritas relatif dalam tujuan ini')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Selesai')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='goals.goal')),
            ],
            options={
                'ordering': ['goal', '-priority', 'created_at'],
            },
        ),
    ]
