# Generated by Django 5.2.1 on 2025-05-30 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kontak')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alamat Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('relationship_type', models.CharField(blank=True, help_text='Contoh: Teman, Keluarga, Rekan Kerja', max_length=50, null=True, verbose_name='Jenis Relasi')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('last_interaction_date', models.DateField(blank=True, null=True, verbose_name='Interaksi Terakhir')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
